name: Cypress Tests

on:
# runs tests every day at 4am
 # schedule:
 # - cron: '*/15 * * * *' # runs every 15th minute
  #  - cron: '0 4 * * *'
 [ push ]

permissions: write-all

jobs:
  cypress-1:
    name: Cypress Test 1
    runs-on: ubuntu-latest
    timeout-minutes: 150
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Run test 1
        if: success() || failure()
        run: npm run test1
      - name: Fetch email 1
        run: npm run email1

      - name: Run test 2
        if: success() || failure()
        run: npm run test2
      - name: Fetch email 2
        run: npm run email2

      - name: Run test 3
        if: success() || failure()
        run: npm run test3
      - name: Fetch email 3
        run: npm run email3

      - name: Run test 4
        if: success() || failure()
        run: npm run test4
      - name: Fetch email 4
        run: npm run email4

      - name: Run test 5
        if: success() || failure()
        run: npm run test5
      - name: Fetch email 5
        run: npm run email5

      - name: Run test 6
        if: success() || failure()
        run: npm run test6
      - name: Fetch email 6
        run: npm run email6

      - name: Run test 7
        if: success() || failure()
        run: npm run test7
      - name: Fetch email 7
        run: npm run email7

      - name: Run test 8
        if: success() || failure()
        run: npm run test8
      - name: Fetch email 8
        run: npm run email8

      - name: Run test 9
        if: success() || failure()
        run: npm run test9
      - name: Fetch email 9
        run: npm run email9

      - name: Run test 10
        if: success() || failure()
        run: npm run test10
      - name: Fetch email 10
        run: npm run email10

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: report/allure-results
          allure_history: allure-history
          keep_reports: 2

      - name: Deploy report to Github Pages1
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          keep_files: true
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

