name: Cypress Tests

on:
# runs tests every day at 4am
 # schedule:
 # - cron: '*/15 * * * *' # runs every 15th minute
  #  - cron: '0 4 * * *'
 [ push ]

jobs:
  Install-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

   # continue-on-error: false
    strategy:
        fail-fast: false



    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16


      - name: Install dependencies
        run: npm i


  Run-Cypress-Test1:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run e2e-test1

  Run-Cypress-Test2:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test2

  Run-Cypress-Test3:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test3


  Run-Cypress-Test4:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test4


  Run-Cypress-Test5:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test5

  Run-Cypress-Test6:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test6


  Run-Cypress-Test7:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test7


  Run-Cypress-Test8:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test8


  Run-Cypress-Test9:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test9


  Run-Cypress-Test10:
    name: Cypress Test 1
    needs: [Install-dependencies]
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run test10



env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #CYPRESS_RECORD_KEY: 6ac5d5b5-cb9c-483b-b332-1a38841fc636
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
