name: Cypress Tests

on:
# runs tests every day at 4am
 # schedule:
 # - cron: '*/15 * * * *' # runs every 15th minute
  #  - cron: '0 4 * * *'
 [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

   # continue-on-error: false
    strategy:
        fail-fast: false



    steps:

   #   - name: Cleanup pre-installed tools
   #     run:
   #         sudo rm -rf /usr/share/dotnet
   #         sudo rm -rf /opt/ghc
   #         sudo rm -rf "/usr/local/share/boost"
   #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16


      - name: Install dependencies
        run: npm i

     #  - name: Cypress run
    #    uses: cypress-io/github-action@v1
    #    with:
    #       env: failOnSnapshotDiff=true


  Run-Cypress-Test1:
    name: Cypress Test 1
    if: success() || failure()
    needs: [cypress-run, Run-Cypress-Test2]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - run: npm run e2e-tests

env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #CYPRESS_RECORD_KEY: 6ac5d5b5-cb9c-483b-b332-1a38841fc636
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
